package io.generators.core;

import java.util.function.Function;
import java.util.function.Predicate;

/**
 * Generates instance of &lt;T&gt;
 *
 * @author Tomas Klubal
 * @author David Bliss
 */
public interface Generator<T> {

    /**
     * Returns generated &lt;T&gt;
     *
     * @return generated <T>
     */
    T next();

    /**
     * Applies function {@code f} to all generated values.
     * @param f function to be applied
     * @param <U> functions result type
     * @return  a new generator of type {@code U} resulting from applying the given function f to each generated  value
     */
    default <U> Generator<U> map(Function<T, U> f) {
        return () -> f.apply(next());
    }


    /**
     * Selects all values generated by this generator which satisfy a predicate.
     * @param p the predicate used to test elements.
     * @return a new generator generating values that satisfy the given predicate p.
     */
    default Generator<T> filter(Predicate<T> p) {
        return () -> {
            T next;
            do {
                next = next();
            } while (!p.test(next));
            return next;
        };
    }


    /**
     * Applies function {@code f} to all generated values.
     * @param f function to be applied
     * @param <U> functions result type
     * @return  a new generator of type {@code U} resulting from applying the given function f to each generated  value
     */
    default <U> Generator<U> flatMap(Function<T, Generator<U>> f) {
        return () -> f.apply(next()).next();
    }
}


