package io.generators.core;

/**
 * Generates values previously consumed. Default and currently the only behaviour is:
 * <ul>
 * <li>If a value hasn't yet been consumed, then next() returns null</li>
 * <li>If multiple values have been consumed, then only the most recent is returned by next()</li>
 * </ul>
 *
 * @author Tomas Klubal
 */
public class ListeningGenerator<T> implements Generator<T>, Consumer<T> {

    private T value;

    /**
     * Consumes and stores  {@code value} which will be afterwards generated if next() is called
     *
     * @param value generated by some generator
     */
    @Override
    public void consume(T value) {
        this.value = value;
    }

    @Override
    public T next() {
        return value;
    }
}
